name: _hi_
favicon: null
layout_spectrum: 0.33676234586164355
typography_spectrum: 0.9856932759284973
title: Hidden Innovations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.03386624134145677
  lightness: 0.753520954400301
  saturation: 0.7859944372903556
  rhythmicContrast: 0.43075426621362567
purpose: []
